# Generated by Django 3.1.5 on 2021-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BantamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('photo', models.ImageField(upload_to='', verbose_name='写真')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('nationality', models.CharField(max_length=20, verbose_name='国籍')),
                ('height', models.IntegerField(verbose_name='身長')),
                ('reach', models.IntegerField(verbose_name='リーチ')),
                ('mma_record', models.CharField(max_length=10, verbose_name='MMA戦績')),
                ('rizin_record', models.CharField(max_length=10, verbose_name='RIZIN戦績')),
            ],
            options={
                'verbose_name_plural': 'BantamPlayer',
            },
        ),
        migrations.CreateModel(
            name='FeatherPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('photo', models.ImageField(upload_to='', verbose_name='写真')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('nationality', models.CharField(max_length=20, verbose_name='国籍')),
                ('height', models.IntegerField(verbose_name='身長')),
                ('reach', models.IntegerField(verbose_name='リーチ')),
                ('mma_record', models.CharField(max_length=10, verbose_name='MMA戦績')),
                ('rizin_record', models.CharField(max_length=10, verbose_name='RIZIN戦績')),
            ],
            options={
                'verbose_name_plural': 'FeatherPlayer',
            },
        ),
    ]
