# Generated by Django 3.1.5 on 2021-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizin_app', '0002_auto_20210127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantamplayer',
            name='mma_record',
            field=models.CharField(max_length=20, verbose_name='MMA戦績'),
        ),
        migrations.AlterField(
            model_name='bantamplayer',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='bantamplayer',
            name='rizin_record',
            field=models.CharField(max_length=20, verbose_name='RIZIN戦績'),
        ),
        migrations.AlterField(
            model_name='featherplayer',
            name='mma_record',
            field=models.CharField(max_length=20, verbose_name='MMA戦績'),
        ),
        migrations.AlterField(
            model_name='featherplayer',
            name='rizin_record',
            field=models.CharField(max_length=20, verbose_name='RIZIN戦績'),
        ),
    ]
