# Generated by Django 3.1.5 on 2021-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizin_app', '0003_auto_20210127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featherplayer',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='ニックネーム'),
        ),
    ]
