# Generated by Django 3.1.5 on 2021-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizin_app', '0004_auto_20210127_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantamplayer',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='featherplayer',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ニックネーム'),
        ),
    ]
