# Generated by Django 3.1.5 on 2021-01-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rizin_app', '0005_auto_20210127_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BantamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('eight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_eight', to='rizin_app.bantamplayer')),
                ('five', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_five', to='rizin_app.bantamplayer')),
                ('four', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_four', to='rizin_app.bantamplayer')),
                ('nine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_nine', to='rizin_app.bantamplayer')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_one', to='rizin_app.bantamplayer')),
                ('seven', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_seven', to='rizin_app.bantamplayer')),
                ('six', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_six', to='rizin_app.bantamplayer')),
                ('ten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_ten', to='rizin_app.bantamplayer')),
                ('three', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_three', to='rizin_app.bantamplayer')),
                ('two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bantamrank_two', to='rizin_app.bantamplayer')),
            ],
            options={
                'verbose_name_plural': 'BantamRank',
            },
        ),
    ]
